#!/usr/bin/env bash
( echo -n 'char *includes='
  grep -hE "^#include|^#gv " interpreter.c functions.c | sort -u | \
  sed 's/^#gv //g; s/\\0/\\\\0/g; s/\\n/\\\\n/g; s/"/\\"/g; s/\\\\"/\\\\\\"/g; s/^/"/; s/$/\\n"/'
  echo '"\0";'

#  echo -n ''
  echo -n 'char *functions='
  grep -vE "^//|^/\*|^extern|^ *$" functions.c | \
    sed 's/\\0/\\\\0/g; s/\\n/\\\\n/g; s/"/\\"/g; s/\\\\"/\\\\\\"/g; s/^/"/; s/$/\\n"/'
  echo '"\0";'

  echo -n 'char *main_body='
  grep -vE "^//|^/\*|^#include|^#gv |^ *$" interpreter.c | \
    sed 's/\\0/\\\\0/g; s/\\n/\\\\n/g; s/"/\\"/g; s/\\\\"/\\\\\\"/g; s/^/"/; s/$/\\n"/'
  echo '"\0";'
) > interpreter.h
